title: Light Stories by Lorena Dumitrașcu

url: "https://lorenadumitrascu.ro"
baseurl:

# Default description in social shares for the jekyll-seo-tag gem
description: Light Stories by Lorena Dumitrașcu.

# Author details for the jekyll-seo-tag gem
author:
  name: Lorena Dumitrașcu
  email: lorenadumitrascu@gmail.com
  twitter: LorenaDumitrasc # twitter username without the @ symbol
  twitter_url: https://twitter.com/LorenaDumitrasc
  facebook: Dumitrascu.Lorena
  facebook_url: https://fb.com/Dumitrascu.Lorena
  instagram: lorena_dumitrascu
  instagram_url: https://www.instagram.com/lorena_dumitrascu/
  image:
    location: "/assets/images/about-3.jpg"
    alt: "Light Stories by Lorena Dumitrașcu"
    width: 604
    height: 403

logo:
  location: /assets/images/logo-big-no-background.png
  alt: "Light Stories by Lorena Dumitrașcu"
  width: 1300
  height: 272

featured:
  path: "/assets/images/portfolio/portraits/R1-02.jpg"
  alt: "Light Stories by Lorena Dumitrașcu"
  width: 1600
  height: 1071

# Social details for the jekyll-seo-tag gem
social:
  name: Light Stories by Lorena Dumitrașcu
  links:
    - https://twitter.com/LorenaDumitrasc
    - https://www.facebook.com/lightstories.ro/
    - https://www.instagram.com/lorena_dumitrascu/

collections:
  projects:
    output: true

paginate: 10
paginate_path: "/blog/:num/"
permalink: pretty

jekyll-archives:
  enabled:
    - "categories"

gems:
  - "jekyll-feed"
  - "jekyll-paginate"
  - "jekyll-archives"
  - "jekyll-sitemap"


defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "index.html"
      type: "pages"
    values:
      layout: "default"

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Instagram
  - Pinterest

google_site_verification: IGPwsFwq4AkUFkJH_ZNSfAZxy5_f5z9egR29iK3UOpA
bing_verification: 6B172C70FEE194C409CD493D635473C3
pintrest_verification: 2de06280859840aabcf8b1270368a7a8
google_analytics_key: UA-3090430-14

facebook:
  page_id: 299519020156870
  app_id: 1761090160786197